services:
  db:
    image: postgres:15-alpine
    container_name: tasks_db_dev
    environment:
      POSTGRES_DB: tasks_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      TZ: UTC
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dev-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-local
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      # Permite recargar la config sin reiniciar el contenedor
      - '--web.enable-lifecycle'
    networks:
      - dev-network
      # Para Linux
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana-local
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - dev-network

# Red privada para que los contenedores hablen entre sí de forma segura
networks:
  dev-network:
    driver: bridge

volumes:
  postgres_data:
  prometheus_data:
  grafana_data: