receivers:
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:4318"

processors:
  batch:
    send_batch_size: 500
    timeout: 10s
  resourcedetection:
    detectors: [ env, system ]
    timeout: 2s
    override: false

extensions:
  basicauth/grafana:
    client_auth:
      username: "${GRAFANA_USER_ID}"
      password: "${GRAFANA_API_KEY}"

exporters:
  prometheusremotewrite:
    endpoint: "${GRAFANA_REMOTE_WRITE_URL}"
    auth:
      authenticator: basicauth/grafana

service:
  extensions: [ basicauth/grafana ]
  telemetry:
    logs:
      level: "warn"
  pipelines:
    metrics:
      receivers: [ otlp ]
      processors: [ resourcedetection, batch ]
      exporters: [ prometheusremotewrite ]