# PLANTILLA: al clonar, cambiar el nombre de este archivo a application-dev.properties
#  y colocar credenciales locales de PostgreSQL.

# Base de datos local
spring.datasource.url=jdbc:postgresql://localhost:5432/tasks_db
spring.datasource.username=NOMBRE_USUARIO
spring.datasource.password=CONTRASEÑA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
