# todo: cambiar todos los .properties a .yml

spring.application.name=task-api

# Selección de perfil
spring.profiles.active=${APP_PROFILE:dev}

# Para que Spring no evite LazyInitializationException. La api tiene 1 sola entidad.
spring.jpa.open-in-view=false