# General
spring.application.name=task-api

# Profile selection
spring.profiles.active=${APP_PROFILE:dev}

# CORS
api.cors.allowed-origins=${ALLOWED_ORIGINS:http://localhost:5173}

# Metrics
management.metrics.tags.application=${spring.application.name}
management.endpoints.web.exposure.include=health,prometheus
management.endpoint.health.show-details=always
management.metrics.limits.uri=100

# Rate limiting
spring.cache.type=jcache
spring.cache.jcache.provider=com.github.benmanes.caffeine.jcache.spi.CaffeineCachingProvider

bucket4j.enabled=true
bucket4j.filters[0].cache-name=buckets
bucket4j.filters[0].url=.*
bucket4j.filters[0].strategy=first
bucket4j.filters[0].rate-limits[0].cache-key=getRemoteAddr()

# To avoid the warning that throws Spring by trying to prevent LazyInitializationException errors
spring.jpa.open-in-view=false