# todo: cambiar todos los .properties a .yml

spring.application.name=task-api

# Profile selection
spring.profiles.active=${APP_PROFILE:dev}

# To avoid the warning that throws Spring by trying to prevent LazyInitializationException errors
spring.jpa.open-in-view=false