# TEMPLATE: change the name of this file to "application-dev.properties"
spring.datasource.url=jdbc:postgresql://localhost:5433/tasks_db
spring.datasource.username=postgres
spring.datasource.password=password

# DB
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# CORS
api.cors.allowed-origins=${ALLOWED_ORIGINS:http://localhost:5173}

# Metrics
management.endpoints.web.exposure.include=*
app.otel.metrics.url=http://localhost:4318/v1/metrics
app.otel.metrics.export-step=5s

# Rate limiting
bucket4j.enabled=false
bucket4j.filters[0].url=.*
bucket4j.filters[0].rate-limits[0].bandwidths[0].capacity=1000
bucket4j.filters[0].rate-limits[0].bandwidths[0].time=1
bucket4j.filters[0].rate-limits[0].bandwidths[0].unit=minutes
bucket4j.filters[0].hide-http-response-headers=false
bucket4j.filters[0].http-response-headers.RateLimit-Limit=1000
bucket4j.filters[0].http-response-headers.RateLimit-Remaining=0
bucket4j.filters[0].http-status-code=too_many_requests
bucket4j.filters[0].http-content-type=application/json
bucket4j.filters[0].http-response-body={ "type": "about:blank", "title": "Too Many Requests", "status": 429, "detail": "You have exceeded the allowed request limit. Please try again later." }

# Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.path=/docs
springdoc.api-docs.path=/api-docs

# Logs
debug=false
logging.level.io.micrometer.otlp=debug
logging.level.io.github.open_telemetry=debug
logging.level.io.micrometer=debug
logging.level.org.springframework.boot.actuate.autoconfigure.metrics=debug
logging.level.root=info
logging.level.org.springframework.cache=debug
logging.level.com.github.benmanes.caffeine.jcache=trace
logging.level.com.giffing.bucket4j=debug
logging.level.com.usuario.todolist.ToDoListApplication=debug
logging.level.org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver=error
logging.pattern.console=%clr(%d{HH:mm:ss}){faint} %clr(%-5level) %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %msg%n
