# =========== CRUDS ===========

### Carga de tarea
POST http://localhost:8080/api/tasks
Content-Type: application/json

{
  "description": "Test de tarea compras 1"
}

### Edición de tarea completa
@idForUpdate = 1
PUT http://localhost:8080/api/tasks/{{idForUpdate}}
Content-Type: application/json

{
  "description": "Test de tarea modificada",
  "completed": false
}

### Tarea con nombre repetido
POST http://localhost:8080/api/tasks
Content-Type: application/json

{
  "description": "Test de tarea modificada"
}

### Patch de tarea
@idForPatch = 1
PATCH http://localhost:8080/api/tasks/{{idForPatch}}
Content-Type: application/json

{
  "completed": true
}

### Eliminación de tarea
@idForDelete = 1
DELETE http://localhost:8080/api/tasks/{{idForDelete}}

### Tarea no encontrada
@idForNotFound = 999
DELETE http://localhost:8080/api/tasks/{{idForNotFound}}

### Ver todas
GET http://localhost:8080/api/tasks

