# =========== FILTROS ===========

### Sin filtros → devuelve TODAS las tareas
GET http://localhost:8080/api/tasks

### Paginación con datos parciales
GET http://localhost:8080/api/tasks?lastId=4&lastDate=2026-04-06T18:44:33&size=1&direction=ASC

### Paginación con datos completos
GET http://localhost:8080/api/tasks?lastId=4&lastDate=2026-04-06T18:44:33&size=1&direction=ASC

### Solo por descripción
GET http://localhost:8080/api/tasks?description=compras

### Descripción parcial
GET http://localhost:8080/api/tasks?description=com

### Solo tareas completadas
GET http://localhost:8080/api/tasks?completed=true

### Solo tareas pendientes
GET http://localhost:8080/api/tasks?completed=false

### Solo por fecha mínima
GET http://localhost:8080/api/tasks?minDate=2026-01-01T12:00

### Solo por fecha máxima
GET http://localhost:8080/api/tasks?maxDate=2026-12-31T12:00

### Por rango de fechas
GET http://localhost:8080/api/tasks?minDate=2026-01-01T12:00&maxDate=2026-12-31T12:00

### Descripción + completadas
GET http://localhost:8080/api/tasks?description=comp&completed=true

### Descripción + rango de fechas
GET http://localhost:8080/api/tasks?description=compras&minDate=2026-01-01T12:00&maxDate=2026-12-31T12:00

### TODOS los filtros combinados
GET http://localhost:8080/api/tasks?description=compr&minDate=2026-01-01T12:00&maxDate=2026-12-31T12:00&completed=false

### Rango de fechas + completadas
GET http://localhost:8080/api/tasks?minDate=2026-01-01T12:00&maxDate=2026-12-31T12:00&completed=true













